### ISSUE TITLE
가독성에 대한 코멘트

### ISSUE THREAD

**Issue by taegon** [haribari01/JBNU_PPP_2024#3]
https://github.com/haribari01/JBNU_PPP_2024/blob/eb9c5f8e6d6beb08b88c5e6c9c34c72daa8ef64e/ppp_hw_check/ppp_07/hw07_4_total_calorie.py#L29-L29

네. 스페이스, 탭, 줄바꿈 등을 이용하시면 됩니다. 한 줄에 동일한 갯수로 정리하면 좋겠지요.
파이참을 쓰면 "Reformat Code(Alt + Ctrl + L)"로 어느정도 정리가 됩니다.
가독성은 정답이 있는 부분이 아니라서, 같이 일하는 동료 혹은 회사에 정한 규칙을 따르면 됩니다.

그리고 데이터 양이 많아지면, 이렇게 코드에 직접 쓰지 않고, 파일에 정리한 후, 파일을 불러서 씁니다.

**Comment by haribari01** [comment]
감사합니다.
