### ISSUE TITLE
과제09

### ISSUE THREAD

**Issue by taegon** [haribari01/JBNU_PPP_2024#4]
아직은 코드가 짧아서 모두 메인에 써도 무리가 없지만, 기능별로 함수를 만드는 연습을 하기 바랍니다.

**Comment by haribari01** [comment]
과제 09 설명에 각각을 함수로 만들지 않아도 된다고 적혀있어서 함수를 만들지 않고 제출했는데, 앞으로는 함수를 만들어서 제출하겠습니다.
